GOOGLE_API_KEY="AIzaSyA88FzLPuWze1FHAWyGh86B3eEfF-Hn5ms"
SUPABASE_URL = "https://xyfqeibnkmiswvsprzxr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5ZnFlaWJua21pc3d2c3ByenhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTYxNzAsImV4cCI6MjA1NTQ3MjE3MH0.2Vr06IgTEj5T-TCMiXAE_78d3k9tw-P8oVbe61BlUKQ"
